In [1]:
import numpy as np
import pandas as pd

#### Data reading

In [3]:
df = pd.read_csv("bikekharido_used_bikes_collected.csv")
df

,bike_name,price,km_driven,ownership,location
0,Activa 3G STD,"₹ 25,000",60000 km,First,Mumbai
1,Maestro Edge 110 Drum Brake Alloy Wheel FI,"₹ 34,000",28000 km,Third,Jaipur
2,XPulse 200 4V,"₹ 95,000",25000 km,Second,Mumbai
3,S1 X,"₹ 75,000",2250 km,First,Kolkata
4,Karizma R,"₹ 16,000",100000 km,First,Hyderabad
...,...,...,...,...,...
1195,2013 Suzuki Access 125 Drum Alloy Bluetooth,"₹ 30,000",20000 km,Second,Ahmadnagar
1196,2019 KTM Duke 390 2017 Edition1,"₹ 1,60,000",21500 km,Above,Mumbai
1197,2019 Bajaj Dominar 400 BS4,"₹ 1,50,000",20000 km,Second,Mumbai
1198,2010 TVS Apache RTR 180,"₹ 18,000",80000 km,Third,Mumbai
1199,2016 Honda CBR 150 R,"₹ 70,000",40000 km,First,Nagpur

#### Data understanding

In [4]:
df.shape

(1200, 5)

In [5]:
df.columns

Index(['bike_name', 'price', 'km_driven', 'ownership', 'location'], dtype='object')

In [8]:
df.head()

,bike_name,price,km_driven,ownership,location
0,Activa 3G STD,"₹ 25,000",60000 km,First,Mumbai
1,Maestro Edge 110 Drum Brake Alloy Wheel FI,"₹ 34,000",28000 km,Third,Jaipur
2,XPulse 200 4V,"₹ 95,000",25000 km,Second,Mumbai
3,S1 X,"₹ 75,000",2250 km,First,Kolkata
4,Karizma R,"₹ 16,000",100000 km,First,Hyderabad

In [7]:
df.dtypes

bike_name    object
price        object
km_driven    object
ownership    object
location     object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   bike_name  1200 non-null   object
 1   price      1200 non-null   object
 2   km_driven  1200 non-null   object
 3   ownership  1200 non-null   object
 4   location   1200 non-null   object
dtypes: object(5)
memory usage: 47.0+ KB

In [9]:
df.describe()

              bike_name     price km_driven ownership location
count              1200      1200      1200      1200     1200
unique              504       128       132         4       97
top     2021 Jawa Perak  ₹ 45,000  10000 km     First    Delhi
freq                 10        56       114       992      218

In [10]:
df.describe(include='object')

              bike_name     price km_driven ownership location
count              1200      1200      1200      1200     1200
unique              504       128       132         4       97
top     2021 Jawa Perak  ₹ 45,000  10000 km     First    Delhi
freq                 10        56       114       992      218

#### Data cleaning

In [11]:
df.isnull().sum()

bike_name    0
price        0
km_driven    0
ownership    0
location     0
dtype: int64

In [12]:
df.duplicated().sum()

602

In [13]:
df = df.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 598

#### Clean the price column

In [14]:
df["price"] = df["price"].str.replace("₹", "", regex=False)
df["price"] = df["price"].str.replace(",", "", regex=False)
df["price"] = df["price"].str.strip()
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["price"].head()

0    25000
1    34000
2    95000
3    75000
4    16000
Name: price, dtype: int64

#### Check invalid prices

In [15]:
print("Invalid price values:", df["price"].isna().sum())

Invalid price values: 0

#### Clean km_driven

In [16]:
df["km_driven"] = df["km_driven"].str.replace("km", "", regex=False)
df["km_driven"] = df["km_driven"].str.strip()

df["km_driven"] = pd.to_numeric(
    df["km_driven"],
    errors="coerce"
)

df["km_driven"].head()

0     60000.0
1     28000.0
2     25000.0
3      2250.0
4    100000.0
Name: km_driven, dtype: float64

In [17]:
print("Invalid km values:", df["km_driven"].isna().sum())

Invalid km values: 1

In [18]:
df[df["km_driven"].isna()]

                                bike_name  price  km_driven ownership location
482  2016 Honda CB Unicorn 160 Disc Brake  28000        NaN     First  Kolkata

In [19]:
## as we got one invalid row means (null value) we can remove that row.
df = df.dropna(subset=["km_driven"]).reset_index(drop=True)

print("Rows after removing invalid km:", len(df))

Rows after removing invalid km: 597

In [20]:
df.describe()

               price      km_driven
count     597.000000     597.000000
mean    97082.137353   27067.435511
std     87883.455752   23590.240374
min     10000.000000     143.000000
25%     42000.000000   10000.000000
50%     75000.000000   20000.000000
75%    130000.000000   35000.000000
max    900000.000000  200000.000000

In [21]:
df.sort_values("price", ascending=False)[
    ["bike_name", "price", "km_driven", "ownership", "location"]
].head(10)

,bike_name,price,km_driven,ownership,location
32,SR125,900000,10000.0,First,Ajmer
196,2023 Hero Splendor Plus i3s,850000,90000.0,First,Bangalore
231,2015 Ducati Monster 795 STD,685000,19200.0,Second,Delhi
456,2022 Kawasaki Z650RS,650000,800.0,First,Delhi
213,2019 Benelli TNT 600i BS4 ABS BS4,470000,20000.0,Third,Delhi
312,2018 Harley-Davidson Street 750 STD,450000,15000.0,Second,Bangalore
172,2023 Kawasaki Ninja 300,365000,1125.0,First,Mumbai
179,2019 Harley-Davidson Street 750 BS6,350000,10000.0,First,Pune
348,2015 Benelli TNT 600i BS4 Limited Edition,340000,35000.0,Second,Coimbatore
354,2022 BMW G 310 RR Style Sport,310000,10000.0,First,Delhi

In [22]:
# Check unusually high prices
df[df["price"] > 500000][
    ["bike_name", "price", "km_driven", "ownership", "location"]
].sort_values("price", ascending=False)

                       bike_name   price  km_driven ownership   location
32                         SR125  900000    10000.0     First      Ajmer
196  2023 Hero Splendor Plus i3s  850000    90000.0     First  Bangalore
231  2015 Ducati Monster 795 STD  685000    19200.0    Second      Delhi
456         2022 Kawasaki Z650RS  650000      800.0     First      Delhi

In [23]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

#### Data quality check

In [25]:
df["ownership"].value_counts()

ownership
First     493
Second     83
Third      16
Above       5
Name: count, dtype: int64

In [26]:
df["location"].value_counts()

location
Delhi            108
Mumbai            61
Bangalore         57
Pune              43
Hyderabad         38
                ...
Visakhapatnam      1
Tezpur             1
Jalandhar          1
Thrissur           1
Ahmadnagar         1
Name: count, Length: 97, dtype: int64

In [27]:
df.dtypes

bike_name     object
price          int64
km_driven    float64
ownership     object
location      object
dtype: object

In [28]:
# final cleaning validation
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:")
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

Rows: 597
Columns: 5
Missing values:
bike_name    0
price        0
km_driven    0
ownership    0
location     0
dtype: int64
Duplicate rows: 0

In [29]:
# save the cleaned data set
df.to_csv("bikekharido_used_bikes_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Final shape:", df.shape)

Cleaned dataset saved successfully!
Final shape: (597, 5)